### ISSUE TITLE
postprocess

### ISSUE THREAD

**Issue by persuelx** [Mandylove1993/CUDA-FastBEV#1]
请问下你的后处理中的解码部分是加入模型中去了嘛？

**Comment by Mandylove1993** [comment]
对的，anchor加进去了，具体可以看onnx结构和export_onnx.py文件的实现

**Comment by Mandylove1993** [comment]
> 请问下你的后处理中的解码部分是加入模型中去了嘛？

对的，anchor加进去了，具体可以看onnx结构和export_onnx.py文件的实现

**Comment by persuelx** [comment]
可以把你的那个模型文件放在百度云么？google下不了

**Comment by persuelx** [comment]
google 中的模型设置下访问权限哦

**Comment by Mandylove1993** [comment]
> google 中的模型设置下访问权限哦

已设置
