### ISSUE TITLE
Custom dataset

### ISSUE THREAD

**Issue by LiuXuan66** [Mandylove1993/CUDA-FastBEV#13]
Hi
 I wonder that if I can use the model provided by you  directly to inference custom dataset(eg. different size, FOV) and just modify the cameras intrinsic and extrinsic( using the provided model to get the valid x y using my intrinsic)? 
  Do cameras intrinsic and extrinsic have great influence to training model? 
Thanks a lot!

**Comment by Mandylove1993** [comment]
You need use custom data intrinsic and extrinsic



---- Replied Message ----
| From | ***@***.***> |
| Date | 09/20/2023 20:38 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [Mandylove1993/CUDA-FastBEV] Custom dataset (Issue #13) |

What I need when i apply this project to custom dataset(eg. different size, intrinsic, FOV), include training and exporting ONXX model? If I need the camera and Lidar extrinsic and intrinsic, and the extrinsic between camera and lidar. Besides, when I train custom dataset if I need to use these intrinsic? Can I use the model provided by you directly? Thanks a lot.

**Comment by LiuXuan66** [comment]
> You need use custom data intrinsic and extrinsic
> […](#)
> ---- Replied Message ---- | From | ***@***.***> | | Date | 09/20/2023 20:38 | | To | ***@***.***> | | Cc | ***@***.***> | | Subject | [Mandylove1993/CUDA-FastBEV] Custom dataset (Issue #13) | What I need when i apply this project to custom dataset(eg. different size, intrinsic, FOV), include training and exporting ONXX model? If I need the camera and Lidar extrinsic and intrinsic, and the extrinsic between camera and lidar. Besides, when I train custom dataset if I need to use these intrinsic? Can I use the model provided by you directly? Thanks a lot. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Thanks for your reply! I have update the comment.

**Comment by LiuXuan66** [comment]
Thanks for your reply!
     But I have updated the comment but not updated in email sent to you by GitHub.
