### ISSUE TITLE
In the dataset，what does（x.tensor,y.tensor,valid_c_idx.tensor) specifically represent?

### ISSUE THREAD

**Issue by linClubs** [Mandylove1993/CUDA-FastBEV#17]
Hi, In the dataset，what does（x.tensor,y.tensor,valid_c_idx.tensor) specifically represent?
Thanks

**Comment by Mandylove1993** [comment]
> Hi, In the dataset，what does（x.tensor,y.tensor,valid_c_idx.tensor) specifically represent? Thanks

x, y represent the projection points of points on the feature, and valid represents whether it is valid on this feature,,you can see dump-data.py for detailed instructions

**Comment by linClubs** [comment]
Thanks,
