### ISSUE TITLE
CuOSD库有问题

### ISSUE THREAD

**Issue by QiTianDaShengDaShi** [Mandylove1993/CUDA-FastBEV#18]
我编译到最后几步，出现了如下问题：
`[ 83%] Building CXX object CMakeFiles/fastbev.dir/src/main.cpp.o
[ 91%] Linking CXX executable fastbev
/usr/bin/ld: CMakeFiles/fastbev.dir/src/common/fastbev_generated_visualize.cu.o: in function nv::create_scene_artist(nv::SceneArtistParameter const&)': tmpxft_000c7437_00000000-6_visualize.cudafe1.cpp:(.text+0x1950): undefined reference to cuosd_context_create()’
/usr/bin/ld: CMakeFiles/fastbev.dir/src/common/fastbev_generated_visualize.cu.o: in function nv::SceneArtistImplement::~SceneArtistImplement()': tmpxft_000c7437_00000000-6_visualize.cudafe1.cpp:(.text._ZN2nv20SceneArtistImplementD2Ev[_ZN2nv20SceneArtistImplementD5Ev]+0x20): undefined reference to cuosd_context_destroy(cuOSDContext*)’

`
有人知道如何解决嘛

**Comment by QiTianDaShengDaShi** [comment]
已经解决，下载Lidar_AI_Solution

**Comment by polarbear122** [comment]
> 已经解决，下载Lidar_AI_Solution

请问下载Lidar_AI_Solution之后，需要如何安装呢？
发生了一个找不到cuosd的错误。

`
[ 83%] Building NVCC (Device) object CMakeFiles/fastbev.dir/src/common/fastbev_generated_visualize.cu.o
/home/agx/Desktop/bev/CUDA-FastBEV/src/common/visualize.cu:25:10: fatal error: cuosd.h: 没有那个文件或目录
   25 | #include <cuosd.h>
      |          ^~~~~~~~~
compilation terminated.
CMake Error at fastbev_generated_visualize.cu.o.Release.cmake:220 (message):
  Error generating
  /home/agx/Desktop/bev/CUDA-FastBEV/build/CMakeFiles/fastbev.dir/src/common/./fastbev_generated_visualize.cu.o


make[2]: *** [CMakeFiles/fastbev.dir/build.make:65：CMakeFiles/fastbev.dir/src/common/fastbev_generated_visualize.cu.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:77：CMakeFiles/fastbev.dir/all] 错误 2
make: *** [Makefile:84：all] 错误 2
`

**Comment by lovelyyoshino** [comment]
把对应的的dependence和libraries放到项目中
![在这里插入图片描述](https://i-blog.csdnimg.cn/direct/887cc95196024928b667804e3bdd2daa.png)
