### ISSUE TITLE
您好，请问下您那边在自己的数据上跑过推理么？

### ISSUE THREAD

**Issue by lucianzhong** [Mandylove1993/CUDA-FastBEV#2]
您好，请问下您那边在自己的数据上跑过推理么？

**Comment by Mandylove1993** [comment]
> 请问下，对内外参的标定精度要求高吗？ 假如不重新训练，直接用模型跑推理，这个可行吗？ 另外，您给出的googledrive链接， 没有权限访问
可以的，虽然效果可能会差一点，，权限你可以再试试？

**Comment by lucianzhong** [comment]
感谢回复， googledrive链接可以下载了

**Comment by lucianzhong** [comment]
再请问一下，跑自己的数据，相机的内参和外参要标定到啥样的精度？ 20m差5个像素点会不会精度低了？ 还有就是车跑起来，需要实时在线校正相机的pitch 角吗？

**Comment by Mandylove1993** [comment]
> 再请问一下，跑自己的数据，相机的内参和外参要标定到啥样的精度？ 20m差5个像素点会不会精度低了？ 还有就是车跑起来，需要实时在线校正相机的pitch 角吗？
在资源有限的平台上，这个方法不太适合使用实时在线矫正，因为这个论文在提出的时候就是希望使用固定的查找表，当然，实时在线矫正是最好的，不过这就需要实时计算查找表来做view transform那一步了

**Comment by lucianzhong** [comment]
收到，感谢
