### ISSUE TITLE
how to obtain these tensors from other datasets or custom datasets, and what are the meanings of these tensors?

### ISSUE THREAD

**Issue by LiuXuan66** [Mandylove1993/CUDA-FastBEV#5]
|-- x.tensor
    |-- y.tensor
    `-- valid_c_idx.tensor

**Comment by Mandylove1993** [comment]
I will upload dump-data.py file later
x.tensor / y.tensor/ valid_c_idx.tensor  means the values x/y/valid in function "backproject_inplace"

**Comment by LiuXuan66** [comment]
> I will upload dump-data.py file later x.tensor / y.tensor/ valid_c_idx.tensor means the values x/y/valid in function "backproject_inplace"

Is that OK? I'm really looking forward to it.

**Comment by Mandylove1993** [comment]
> > I will upload dump-data.py file later x.tensor / y.tensor/ valid_c_idx.tensor means the values x/y/valid in function "backproject_inplace"
> 
> Is that OK? I'm really looking forward to it.

Updated

**Comment by LiuXuan66** [comment]
> > > I will upload dump-data.py file later x.tensor / y.tensor/ valid_c_idx.tensor means the values x/y/valid in function "backproject_inplace"
> > 
> > 
> > Is that OK? I'm really looking forward to it.
> 
> Updated

Wow!!! Thank you so much!
