### ISSUE TITLE
你好，运行bash tool/run.sh 报错

### ISSUE THREAD

**Issue by xqh5201314** [Mandylove1993/CUDA-FastBEV#6]
/usr/bin/ld: 找不到 -lspconv
/usr/bin/ld: 找不到 -lspconv
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/fastbev_core.dir/build.make:224：libfastbev_core.so] 错误 1
make[1]: *** [CMakeFiles/Makefile2:105：CMakeFiles/fastbev_core.dir/all] 错误 2
make: *** [Makefile:84：all] 错误 2

**Comment by QiTianDaShengMaoHuiFei** [comment]
你这个安装spconv就行了
`git clone -b v1.2.1 https://github.com/traveller59/spconv.git --recurse-submodules
`

**Comment by JLeere** [comment]
作者调用了这个开源库： https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution，我看路径文件夹这些都吻合

**Comment by JLeere** [comment]
https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/tree/master/libraries
作者在这个框架下写的代码，里面含有需要的依赖库

**Comment by heurry** [comment]
it doesn't need install spconv, just change ../ to ./
  ./dependencies/stb
  ./dependencies/pybind11/include
  ./libraries/cuOSD/src
  ./libraries/3DSparseConvolution/libspconv/include

**Comment by lovelyyoshino** [comment]
```bash
cd ~
git clone -b v1.2.1 https://github.com/traveller59/spconv.git --recurse-submodules
cd spconv
```
打开 setup.py 脚本，找到 build_extension 函数，找到 cuda_flags 这个参数，在下方添加如下代码

```bash
cuda_flags += ["-gencode", "arch=compute_52,code=sm_52",
                "-gencode", "arch=compute_60,code=sm_60",
                "-gencode", "arch=compute_61,code=sm_61",
                "-gencode", "arch=compute_70,code=sm_70",
                "-gencode", "arch=compute_75,code=sm_75",
                "-gencode", "arch=compute_80,code=sm_80",
                "-gencode", "arch=compute_86,code=sm_86",
                "-gencode", "arch=compute_86,code=compute_86"]

```
打开 CMakeLists.txt ，在其内添加如下代码：

```bash
set(CMAKE_VERBOSE_MAKEFILE ON)
```
执行编译命令：

```bash
python setup.py bdist_wheel
# THC/THCNumerics.cuh: No such file or directory: https://blog.csdn.net/zjsdbkb88/article/details/136454689
```
编译完成后生成的动态库文件在 build 文件夹下以 lib 开头的文件夹内，开发时主要使用的是 `libcuhash.so` 及 `libspconv.so` 这两个文件，可以将这两个文件拷贝到 /usr/local/lib 目录下。头文件在项目根目录的 include 文件夹下，可以将其内的所有文件放到 `/usr/local/include` 目录。

**Comment by bbqq7788** [comment]
#error You need C++17 to compile PyTorch和#error C++17 or later compatible compiler is required to use ATen.
我的g++和gcc版本都为11.4.0，我需要将g++升级为11.7吗？
