### ISSUE TITLE
the visualize code of the demo showed in readme

### ISSUE THREAD

**Issue by LiuXuan66** [Mandylove1993/CUDA-FastBEV#7]
Could you please share the visualize code of the demo showed in readme

**Comment by Mandylove1993** [comment]
I will upload later~

**Comment by LiuXuan66** [comment]
> I will upload later~

Thanks for your great work!!!

**Comment by LiuXuan66** [comment]
> I will upload later~

The demo picture  showed in main page is using resnet18int8 model to inference or other model? Why I can't get such good results using the provided model.

**Comment by QiTianDaShengDaShi** [comment]
老弟，你的可视化代码整好了嘛
