### ISSUE TITLE
关于epoch20.pth

### ISSUE THREAD

**Issue by fengguibinyn** [Mandylove1993/CUDA-FastBEV#8]
用官方提供的pth运行ptq_bev.py貌似并不能通过，能提供下您那变训练的吗

**Comment by Mandylove1993** [comment]
用官方的代码，使用我提供的config，训练后的pth就可以用了

**Comment by nieyan** [comment]
Could you upload a   “ ptq/pth/epoch_20.pth“  file to quick check  ptq/dump-data.py ？ thanks!
